version: '4.14.1'

services:
  db:
    image: postgres:latest
    container_name: pd-project
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: admin
    ports:
      - 5434:5432
    volumes:
      - db_data_volume:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
volumes:
    db_data_volume: